### ISSUE TITLE
do you ever just... you know?

### ISSUE THREAD

**Issue by jdshaeffer** [clarkshaeffer/sudoku#1]
Everyday when you're walking down the street, everybody that you meet
Has an original point of view
And I say hey what a wonderful kind of day.
Where you can learn to work and play
And get along with each other
You got to listen to your heart
Listen to the beat
Listen to the rhythm, the rhythm of the street
Open up your eyes, open up your ears
Get together and make things better by working together
It's a simple message and it comes from the heart
Believe in yourself (echo: believe in yourself)
Well thats the place to start (to start)
And I say hey what a wonderful kind of day
Where you learn to work and play
And get along with each other

**Comment by clarkshaeffer** [comment]
Good catch. New patch should fix the bug.
Closing this thread.
